version: "3.9"

services:
  postgres:
    container_name: app2_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_db_user
      POSTGRES_PASSWORD: postgres_db_password
    volumes:
      - ./postgres/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  web-service:
    image: new_project_mlops:latest
    container_name: app2
    environment:
      POSTGRES_HOST: app2_db
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_db_user
      POSTGRES_PASSWORD: postgres_db_password
    ports:
      - "4000:4000"
